// <auto-generated />
using System;
using CampusToolbox.Service.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CampusToolbox.Service.Migrations.Trade
{
    [DbContext(typeof(TradeContext))]
    [Migration("20190424132002_update-price")]
    partial class updateprice
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CampusToolbox.Model.Back.Trade.DemandModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BaseId");

                    b.Property<string>("Collage");

                    b.Property<decimal>("PriceMax");

                    b.Property<decimal>("PriceMin");

                    b.Property<int>("PublisherId");

                    b.HasKey("Id");

                    b.HasIndex("BaseId");

                    b.ToTable("Demands");
                });

            modelBuilder.Entity("CampusToolbox.Model.Back.Trade.SupplyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BaseId");

                    b.Property<string>("Collage");

                    b.Property<string[]>("Images");

                    b.Property<decimal>("PriceMax");

                    b.Property<decimal>("PriceMin");

                    b.Property<int>("PublisherId");

                    b.HasKey("Id");

                    b.HasIndex("BaseId");

                    b.ToTable("Supplies");
                });

            modelBuilder.Entity("CampusToolbox.Model.Back.Trade.TradeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BuyerId");

                    b.Property<int>("GoodId");

                    b.Property<int>("Level");

                    b.Property<string>("UniName");

                    b.HasKey("Id");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("CampusToolbox.Model._Shared.Account._SharedTradeGoodModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AvailableTo");

                    b.Property<string>("Desc");

                    b.Property<bool>("IsAvailable");

                    b.Property<string>("Name");

                    b.Property<DateTime>("PublishDate");

                    b.Property<string>("Tag");

                    b.HasKey("Id");

                    b.ToTable("_SharedTradeGoodModel");
                });

            modelBuilder.Entity("CampusToolbox.Model.Back.Trade.DemandModel", b =>
                {
                    b.HasOne("CampusToolbox.Model._Shared.Account._SharedTradeGoodModel", "Base")
                        .WithMany()
                        .HasForeignKey("BaseId");
                });

            modelBuilder.Entity("CampusToolbox.Model.Back.Trade.SupplyModel", b =>
                {
                    b.HasOne("CampusToolbox.Model._Shared.Account._SharedTradeGoodModel", "Base")
                        .WithMany()
                        .HasForeignKey("BaseId");
                });
#pragma warning restore 612, 618
        }
    }
}
