// <auto-generated />
using System;
using System.Collections.Generic;
using CampusToolbox.Service.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CampusToolbox.Service.Migrations.HHI
{
    [DbContext(typeof(HHIContext))]
    partial class HHIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CampusToolbox.Model.Back.Utils.HappyHandingIn.HHIBackModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<List<string>>("Images");

                    b.Property<DateTime>("LastCommitTime");

                    b.Property<int>("OwnerId");

                    b.Property<int>("TaskId");

                    b.HasKey("Id");

                    b.ToTable("backModel");
                });

            modelBuilder.Entity("CampusToolbox.Model.Back.Utils.HappyHandingIn.HHIClassModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Name");

                    b.HasKey("Id");

                    b.ToTable("classModels");
                });

            modelBuilder.Entity("CampusToolbox.Model.Back.Utils.HappyHandingIn.HHIModel+AssignedTaskModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DeadLine");

                    b.Property<string>("Description");

                    b.Property<bool>("IsSubItemFolder");

                    b.Property<bool>("IsSubItemImage");

                    b.Property<string>("Name");

                    b.Property<int>("OwnerId");

                    b.Property<string>("Path");

                    b.Property<int?>("PrefixId");

                    b.Property<string>("PrefixName");

                    b.Property<string>("Regex");

                    b.HasKey("Id");

                    b.HasIndex("PrefixId");

                    b.ToTable("workModels");
                });

            modelBuilder.Entity("CampusToolbox.Model.Back.Utils.HappyHandingIn.HHIModel+PrefixModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("End");

                    b.Property<List<string>>("ExcludeList");

                    b.Property<List<string>>("IncludeList");

                    b.Property<List<int>>("IndexList");

                    b.Property<List<string>>("MemberNameList");

                    b.Property<string>("Name");

                    b.Property<int>("Start");

                    b.HasKey("Id");

                    b.ToTable("prefixModels");
                });

            modelBuilder.Entity("CampusToolbox.Model.Back.Utils.HappyHandingIn.HHIModel+AssignedTaskModel", b =>
                {
                    b.HasOne("CampusToolbox.Model.Back.Utils.HappyHandingIn.HHIModel+PrefixModel", "Prefix")
                        .WithMany()
                        .HasForeignKey("PrefixId");
                });
#pragma warning restore 612, 618
        }
    }
}
