// <auto-generated />
using System;
using CampusToolbox.Service.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CampusToolbox.Service.Migrations.TokenSession
{
    [DbContext(typeof(TokenSessionContext))]
    [Migration("20190321123005_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CampusToolbox.Model.Back.Account.AccountBackModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AbsVisiableId");

                    b.Property<int>("Identity");

                    b.Property<int?>("RelieableId");

                    b.Property<int?>("SysId");

                    b.HasKey("Id");

                    b.HasIndex("AbsVisiableId");

                    b.HasIndex("RelieableId");

                    b.HasIndex("SysId");

                    b.ToTable("AccountBackModel");
                });

            modelBuilder.Entity("CampusToolbox.Model.Back.Account._SharedAbsolutelyVisiableAccountModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("College");

                    b.Property<string>("NickName");

                    b.HasKey("Id");

                    b.ToTable("_SharedAbsolutelyVisiableAccountModel");
                });

            modelBuilder.Entity("CampusToolbox.Model.Back.Account._SharedRelieableAccountModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("District");

                    b.Property<string>("Email");

                    b.Property<int>("Grade");

                    b.Property<bool>("IsConfirmed");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.HasKey("Id");

                    b.ToTable("_SharedRelieableAccountModel");
                });

            modelBuilder.Entity("CampusToolbox.Model.Back.Account._SharedSystemAccountModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PasswordEncrypted");

                    b.HasKey("Id");

                    b.ToTable("_SharedSystemAccountModel");
                });

            modelBuilder.Entity("CampusToolbox.Model.Security.TokenModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AccountId");

                    b.Property<string>("Token");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("CampusToolbox.Model.Back.Account.AccountBackModel", b =>
                {
                    b.HasOne("CampusToolbox.Model.Back.Account._SharedAbsolutelyVisiableAccountModel", "AbsVisiable")
                        .WithMany()
                        .HasForeignKey("AbsVisiableId");

                    b.HasOne("CampusToolbox.Model.Back.Account._SharedRelieableAccountModel", "Relieable")
                        .WithMany()
                        .HasForeignKey("RelieableId");

                    b.HasOne("CampusToolbox.Model.Back.Account._SharedSystemAccountModel", "Sys")
                        .WithMany()
                        .HasForeignKey("SysId");
                });

            modelBuilder.Entity("CampusToolbox.Model.Security.TokenModel", b =>
                {
                    b.HasOne("CampusToolbox.Model.Back.Account.AccountBackModel", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");
                });
#pragma warning restore 612, 618
        }
    }
}
